### PR TITLE
Add Working with Ghost and Hexo

### PR DESCRIPTION
**Pull request by daviddarnes**
We're written some official docs on how to use Ghost with Hexo, hope people find this useful 🚀

Link added: https://ghost.org/docs/api/v2/hexo/

### CODE REVIEW

**Comment by SukkaW** [comment]
LGTM, The instruction looks great!

**Review by SukkaW — APPROVED** [review]

**Comment by SukkaW** [comment]
cc @NoahDragon @YoshinoriN @tomap

**Comment by daviddarnes** [comment]
Thanks very much @SukkaW!

**Review by tomap — APPROVED** [review]

**Review by yoshinorin — APPROVED** [review]
@daviddarnes 
It's awesome! Thank you for your contribution :)

**Comment by daviddarnes** [comment]
Thanks @YoshinoriN!

**Pull request merged**
